name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "23 19 8 * *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/poetry-upgrade.yml@7b06919181c4d87ef735d84bcb87c9cf3de1f4d0 # v1
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}
